### PR TITLE
Add more extensibility for the conditions that make a field a date

### PR DESCRIPTION
**Pull request by gfcapalbo**
Currently a date field is identified if starts with "date" . I extend this a little bit with a lambda function because i also need requested_date in my  templates to be evaled like a date.
This looks like a nice way to extend that depending on one's needs for date fields

### CODE REVIEW

**Comment by alexis-via** [comment]
Maybe we should just write:
`if 'date' in k:`

**Comment by alexis-via** [comment]
or, if we don't want to make it too wide:
`if k.startswith('date') or k.endswith('date'):`

**Comment by gfcapalbo** [comment]
I think start and end is enough. No lambda. pushing

**Comment by hbrunn** [comment]
I still think there should be an extra key `types` for templates that allows arbitrary typecasts. This already [happens for lines](https://github.com/m3nu/invoice2data/blob/master/invoice2data/template.py#L262), and you can simply use [coerce_type](https://github.com/m3nu/invoice2data/blob/master/invoice2data/template.py#L132) then

**Pull request merged**
