### PR TITLE
Add support for sum_ prefix for amount fields

### PR DESCRIPTION
**Pull request by alexis-via**
Update documentation to explain the use of sum_ prefix
Add a template that use the sum_ prefix

### CODE REVIEW

**Comment by alexis-via** [comment]
@m3nu What do you think about this new feature ?

**Comment by m3nu** [comment]
What does it do?

Did you get my email regarding Google Summer of Code. Currently I'm collecting ideas for this that could be implemented by students. If you have time, I'd like to add you as co-mentor.

**Comment by alexis-via** [comment]
@m3nu I updated the documentation :) In summary: if, in the invoice, you have to sum several numbers to get the total untaxed amount or the total tax amount (or any other amount), you are now able to define several regexp to extract several numbers and sum them.

I'll answer you about GSoC.

**Comment by alexis-via** [comment]
@m3nu I haven't found you email about GSoC... could you send it again please ?

**Comment by m3nu** [comment]
I sent it to `alexis [at] via.ecp.fr`. Not sure that's the right email. @alexis-via

**Comment by alexis-via** [comment]
Yes, that's the right mail, but I didn't find it when I looked in the history. Did you send it again yesterday ?

**Comment by m3nu** [comment]
Resent it just now.

**Comment by m3nu** [comment]
Sent you one more email with an update on this matter. Hope you can receive it.

**Comment by alexis-via** [comment]
I just replied you. I was extremely busy at the beginning of this year, but it's better now; sorry for the emails without answer.

Are you OK to merge this PR ? Do you understand the need for this feature ?

**Comment by m3nu** [comment]
It's fine, as long as no old stuff is broken. I'll merge it, but you can fix any errors happening in the CI.

**Pull request merged**
