### PR TITLE
Tests for command line tools

### PR DESCRIPTION
**Pull request by duskybomb**
A small step to make the code modular and easier for CLI tests
Added basic Tests for Command Line Tools
@dpocock

### CODE REVIEW

**Comment by duskybomb** [comment]
@m3nu can you review the commit

**Comment by m3nu** [comment]
Looks alright. Will run it in full tomorrow morning.

**Comment by m3nu** [comment]
Merged. Just one thing: tabs?? ;-)

**Comment by m3nu** [comment]
So far your tests don't test anything. We should still add that.

**Comment by duskybomb** [comment]
@m3nu Instead of tapping `space` 2 (or 4) times I can tap `tab` once. 🤣 
And Yes they don't but this is the basic template.

**Pull request merged**
