### PR TITLE
adding extract option for pdftotext

### PR DESCRIPTION
**Pull request by duskybomb**
* Adding an option for author to add extract option like `-table` or `-layout`.
 * Refactored `main.py`, `invoice_template.py` and `pdftotext.py` to PEP-8

Solves #108

### CODE REVIEW

**Comment by duskybomb** [comment]
@m3nu Merge this?

**Comment by m3nu** [comment]
We can't add if-conditions like that. To pass arguments to the extract module, there should be a universal way that works the same for all modules.

**Comment by duskybomb** [comment]
But this feature is only for pdftotext module, how can we make it universal when no other module uses such extract layouts?

**Comment by m3nu** [comment]
Other extract options may need special settings as well. If you want to pass those, there needs to be a universal way. Like ffmpeg has for example for filter options.

If you think it's not worth doing it properly we can't add this feature for now.

**Pull request closed without merging**
