### PR TITLE
Update to_json.py

### PR DESCRIPTION
**Pull request by duskybomb**

### CODE REVIEW

**Comment by m3nu** [comment]
Are you trying to get as many PRs as possible ;-) ?

**Comment by duskybomb** [comment]
@m3nu I forgot to add json file and as I was about to commit it, you merged it. Sorry, I will be more careful from now on.

**Comment by m3nu** [comment]
No worries. Let's hop the test succeeds now.

**Comment by m3nu** [comment]
Still fails. The output doesn't even have the same number of result files.

I'm disabling the test for now until we have time for a proper solution. Too important to rush it.

**Comment by duskybomb** [comment]
I dont know why is it happening, tests are passing in my environment.

**Pull request merged**
