### PR TITLE
Initial prototype of invoice2data GUI

### PR DESCRIPTION
**Pull request by uditjuneja1**
This is an initial prototype, happy to get feedback on this. 
Some of the features we could add:
- Specifying options like output formats, extractors, file name.
- Support for batch extraction (select multiple PDF file)

I am looking forward to contribute more towards this project as part of my GSoC project. I would like to  integrate invoice2data with Mail platform.

### CODE REVIEW

**Comment by uditjuneja1** [comment]
@m3nu happy to hear your feedback on this. Please note that this is still an initial prototype. I am also interested in applying for the [GSoC project](https://wiki.debian.org/SummerOfCode2018/Projects/ExtractingDataFromPDFInvoicesAndBills) this year.

**Comment by m3nu** [comment]
I can't merge a prototype into the production version. Still interesting to see your approach. We may pick it up later after more planning and definition of the requirements.

**Comment by uditjuneja1** [comment]
Thanks for replying back. The idea was to get a feedback on the
implementation, I would like to discuss the idea further with you. As you
mentioned, can we discuss the idea further and try to improve upon this.

Regards.

**Comment by uditjuneja1** [comment]
Thanks for replying back. The idea was to get a feedback on the
implementation, I would like to discuss the idea further with you. As you
mentioned, can we discuss the idea further and try to improve upon this.

I have also created a new pull request with many new features.

**Pull request closed without merging**
