### PR TITLE
[RFR] keep order while loading yaml files

### PR DESCRIPTION
**Pull request by hbrunn**
as discussed in https://github.com/m3nu/invoice2data/pull/22#issuecomment-270039508, here's the PR to use `OrderdDict`s to hold the data

### CODE REVIEW

**Comment by m3nu** [comment]
Awesome. Looks good. Will merge and rearrange a bit today or tomorrow. We can probably move all those helper-functions to some other file.

**Comment by m3nu** [comment]
Merged. Also renamed some of the files to make it easier to understand. Had to use `items()` instead of `iteritems()` for `OrderedDict`. Optionally you can test your commits by running `tox` in the project folder. This should run some test using various Python versions.

**Comment by hbrunn** [comment]
thanks for the fixes and apologies for them being necessary in the first place, I'm a bit too focused on python2.7 still

**Comment by m3nu** [comment]
No worries. We're all learning here. Also added you to the list of contributors. Pre-empt credit for the item-feature ;-)

**Pull request merged**
