### PR TITLE
Added currency data to output files.

### PR DESCRIPTION
**Pull request by duskybomb**
I think currency is a useful data to have in the output files. Hence, I added the currency data to all the output formats (csv, json, xml)
@dpocock

### CODE REVIEW

**Comment by duskybomb** [comment]
@m3nu is this good?

**Comment by m3nu** [comment]
Will check by next week as this is a bigger change.

**Comment by duskybomb** [comment]
@m3nu can you review this now? :stuck_out_tongue:

**Comment by m3nu** [comment]
Sorry for the delay. Almost did it today, but wanted to take some time to run it properly. Give me 1 more day.

**Comment by duskybomb** [comment]
I understand you might be busy, but I am getting too anxious.  @m3nu

**Comment by m3nu** [comment]
Merged. Will see if it breaks something and fix it then.

**Comment by m3nu** [comment]
Uh. Tests already failed. Let's see what's broken here.

**Comment by m3nu** [comment]
Your comparison-tests are all failing. Your should fix them.

**Comment by m3nu** [comment]
Did you run the tests before opening this PR?

**Comment by duskybomb** [comment]
@m3nu Yes, I did run the tests. It showed 25 Tests passed. Let me re-run.

**Comment by duskybomb** [comment]
@m3nu the problem is, previous commits added new pdfs to `test/pdfs/` folder. Should we remove those pdfs or add new testing?

**Comment by m3nu** [comment]
I see. New testing would be better.

**Comment by m3nu** [comment]
Could it ignore new PDFs? In case authors add new PDFs without adding tests?

**Comment by duskybomb** [comment]
I am working on it. Will most probably hard code the file names.

**Comment by m3nu** [comment]
There could be a filename > result mapping.

Let's just do a quick fix here and open a new issue to solve it properly later.

**Pull request merged**
