### PR TITLE
Export all fields

### PR DESCRIPTION
**Pull request by duskybomb**
Implemented dumping all fields to json and csv.
I need to add it for xml, I want to ask can I use an external library like `dicttoxml`?
#114

### CODE REVIEW

**Comment by m3nu** [comment]
No need for XML.

**Comment by duskybomb** [comment]
Okay no problem, will do it.

**Comment by m3nu** [comment]
If a user takes the effort to define his fields in the template, he probably needs them. Of not, he just ignores them in the export. So having options here adds needless clutter.

**Comment by m3nu** [comment]
To save you time, you should write down the changes you intend to do for each issue before coding them. Then I can make sure you are on the right track.

**Comment by duskybomb** [comment]
Can you merge #120, so that I can then remove conflicts that will appear in #118  and then work on adding docstrings #119 ?

**Comment by m3nu** [comment]
Merging. Please outline the proposed changes for the other features before implementing anything. So we can discuss and go over them before coding anything.

**Pull request merged**
